### ISSUE TITLE
The following resource(s) failed to create: [MyDedicatedHost] - Status code 500

### ISSUE THREAD

**Issue by yngvark** [DanielRDias/terraform-aws-dedicated-host#7]
When using 0.3.0, I'm getting this error:

> Do you want to perform these actions?
>   Terraform will perform the actions described above.
>   Only 'yes' will be accepted to approve.
> 
>   Enter a value: yes
> 
> module.dedicated-host.aws_cloudformation_stack.dedicated_hosts: Creating...
> module.dedicated-host.aws_cloudformation_stack.dedicated_hosts: Still creating... [10s elapsed]
> module.dedicated-host.aws_cloudformation_stack.dedicated_hosts: Still creating... [20s elapsed]
> module.dedicated-host.aws_cloudformation_stack.dedicated_hosts: Still creating... [30s elapsed]
> module.dedicated-host.aws_cloudformation_stack.dedicated_hosts: Still creating... [40s elapsed]
> module.dedicated-host.aws_cloudformation_stack.dedicated_hosts: Still creating... [50s elapsed]
> module.dedicated-host.aws_cloudformation_stack.dedicated_hosts: Still creating... [1m0s elapsed]
> module.dedicated-host.aws_cloudformation_stack.dedicated_hosts: Still creating... [1m10s elapsed]
> module.dedicated-host.aws_cloudformation_stack.dedicated_hosts: Still creating... [1m20s elapsed]
> module.dedicated-host.aws_cloudformation_stack.dedicated_hosts: Still creating... [1m30s elapsed]
> ╷
> │ Error: error waiting for CloudFormation Stack (arn:aws:cloudformation:eu-west-1:xxxxxxxxxxx:stack/dedicated-hosts-stack/6639cca0-fe9c-11ec-be5c-0ae3b4793f3b) create: failed to create CloudFormation stack, rollback requested (ROLLBACK_COMPLETE): ["The following resource(s) failed to create: [MyDedicatedHost]. Rollback requested by user." "Resource handler returned message: \"An internal error has occurred (Service: Ec2, Status Code: 500, Request ID: 9cfd01a0-15d6-4354-8218-34429d680e47, Extended Request ID: null)\" (RequestToken: b115ed36-3fb9-51bc-7fd6-d1e032643693, HandlerErrorCode: GeneralServiceException)"]
> │ 
> │   with module.dedicated-host.aws_cloudformation_stack.dedicated_hosts,
> │   on .terraform/modules/dedicated-host/main.tf line 1, in resource "aws_cloudformation_stack" "dedicated_hosts":
> │    1: resource "aws_cloudformation_stack" "dedicated_hosts" {
> │ 
> ╵
> Releasing state lock. This may take a few moments...

I'm not sure what's wrong.

**Comment by DanielRDias** [comment]
Hi @yngvark sorry for the long delay checking this.
I just tested it, and it worked for me, but I had to change my region because AWS had no capacity in the region of the example.
Was this the same issue you faced?

**Comment by yngvark** [comment]
I don't know if capacity was the problem, I would have to retest. I'll let you know if I come back to this.
